version: '3'
services:
  elk:
    image: sebp/elk
    environment:
      - ES_CONNECT_RETRY=100
    volumes:
      - "./logstash/12-insync.conf:/etc/logstash/conf.d/12-insync.conf"
      - "./logstash/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf"
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  filebeat:
    build:
      context: ./filebeat
    user: root
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "./logs/insync-api.log:/var/log/insync-api.log"
    command: ["filebeat", "-e", "-strict.perms=false"]
  solr:
    image: noterik/insync-solr
    ports:
      - "${DOCKER_SOLR_PORT}:8983"
    volumes:
      - /opt/solr/server/solr/mycores
    restart: always
  db:
      image: noterik/insync-db
      restart: always
  schema:
      image: noterik/insync-json-schema
      ports:
        - "${DOCKER_SCHEMA_PORT}:80"
      restart: always
  api:
      image: noterik/insync-api:1.1
      env_file:
        - ./.env
      depends_on:
        - schema
        - db
      restart: always
      volumes:
        - ../insync-api:/opt/app
        - /opt/app/vendor
        - ./logs/insync-api.log:/var/log/insync-api.log
      ports:
        - "${DOCKER_API_PORT}:80"
      links:
        - schema
        - db